
# def main_function():
#     """Main function generated by me"""
#     pass 

# print(main_function) #<function main_function at 0x000001C5F81B8A60>
# print(main_function()) # None
# print(main_function.__doc__) # Main function generated by me


# def math_pow(a,b):
#     return a ** b 

# print(math_pow(2,2)) # 4
# print(math_pow(2,10)) # 1024

# print(math_pow(2)) # TypeError: math_pow() missing 1 required positional argument: 'b'
# print(math_pow(2,3)) # 8
# print(math_pow(a=2,b=2)) # 4


# def concat_string(string1, string2,string3=""):
#     return string1 + string2 + string3

# print(concat_string("Baqlajon" , "Apple", "Noutbuk")) # BaqlajonAppleNoutbuk
# print(concat_string("Baqlajon" , "Noutbuk")) # BaqlajonNoutbuk
# print(concat_string("Baqlajon" , "Noutbuk", "Olma")) # BaqlajonNoutbukOlma
# def plus(x,y):
#     return int(x)+int(y) 
# def minus(x,y):
#     return int(x)-int(y) 
# def division(x,y):
#     return int(x)//int(y) 
# def multiple(x,y):
#     return int(x)*int(y) 

# num1 = input("Num 1 ? \n:")
# num2 = input("Num 2 ? \n:")
# ex = input("Operation ? \n:")
# if ex == "+":
#     print(plus(num1,num2))
# elif ex == "-":
#     print(minus(num1,num2))
# elif ex == "/":
#     print(division(num1,num2))
# elif ex == "*":
#     print(multiple(num1,num2))
# else:
#     print("Not supported operator")

# task 1

# 10 ta kompnaiya xodimining ism va familyasi + xarbiy xizmatga borgan bormagani berilgan ro'yhat bor , check_personal nomli funksiya yozing va ushbu royhatdan xarbiy xizmatga borgan ishchilarni alohida royhat qilib saralab yozing 
# input ;  personal = [
#     {
#         "name":"John Doe",
#         "military":True
#     },
#     {
#         "name":"Sara Connor",
#         "military":False
#     },
#     ...
#     ]
# output: result = [
#     {
#         "name":"John Doe",
#         "military":True
#     },
# ]